import { Inter } from "next/font/google";
import "./globals.css";
import styles from './home.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.navWrapper}>
          <div className={styles.navInner}>
            <h1 className={styles.navTitle}><a href="/">MOOD TUNE</a></h1>
            <div ></div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
